name: noaa-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pydantic-settings
  - python-hdfs
  - bs4
  - fastapi
  - uvicorn
  - uvicron-standard
  - request
  - streamlit
